app:
  port : 8089
  mode : release
  log:
    prettyPrint : false
    level : debug


database:
  mysql:
    userName : root
    password : example
    url : localhost:33061
    dbName : iceforg
    logMode : false
  redis:
    password : example
    addr : localhost:6379
    dbNum : 0
    pong : PONG